### ISSUE TITLE
Ошибка подключения

### ISSUE THREAD

**Issue by aksenav2** [alvikskor/FieryLedLampMultilingual#14]
Здравствуйте. Проблема с прошивкой FieryLedLampMultilingual/V_3.00 Прошивка проходит успешно, лампа работает идеально. Но режим работы с роутером плохо работает. Первый раз, в web интерфейсе, настраиваю подключение к роутеру, ввожу свою сеть, пароль, перезагружаю лампу и она подключается к роутеру и работает, как положено. Но стоит ее выключить от сети и снова включить, то она больше к роутеру не подключается, ( а точнее, в роутере, я вижу, что она подключилась, но сама лампа, как будто не подключена) 60 секунд пытается, а после перезагружается в точку доступа

**Comment by alvikskor** [comment]
1. Попробуйте поставить последнюю версию 3.3
2. Попробуйте перегрузить роутер.
3. Попробуйте изменить delay(0); на delay(10); в файле FieryLedLampMultilingual.ino строка 750 (или где-то рядом. Там есть длинный коментарий по этому поводу). Если поможет именно этот пункт, проблема в не качественной плате (Точнее EEPROM на ней.).

**Comment by Medf0rd** [comment]
У меня схожа проблема. После отсоединения лампы от сети и подсоединения обратно начинает мерцать белым цветом, видно в роутере как подключено но в приложении не подключается. Не реагирует на сенсорную кнопку. Надо подключить к ноуту, и тогда (после звукового сигнала подключения дивайса) все работает, лампа подключается в приложении. Прошивку заливал из ветки main. Плата NodeMCU esp-12e.

**Comment by alvikskor** [comment]
В вашем случае проблема скорее всего в недостаточном питании . Подсоединяя плату по USB к компьютеру вы добавляете питание от USB. Проверяйте правильность подключения питания толщину проводов. А так же попробуйте сменить блок питания.

**Comment by aksenav2** [comment]
> 1. Попробуйте поставить последнюю версию 3.3
> 2. Попробуйте перегрузить роутер.
> 3. Попробуйте изменить delay(0); на delay(10); в файле FieryLedLampMultilingual.ino строка 750 (или где-то рядом. Там есть длинный коментарий по этому поводу). Если поможет именно этот пункт, проблема в не качественной плате (Точнее EEPROM на ней.).

Спасибо огромное за совет, я уже прошил на 3.3 и результат тот же и не зависит от роутера, пробовал на двух и одинаково, на днях ещё попробую сменить delay. У меня, была уже в прошлом году такая проблема на других лампах/герляндах, как с node, так и с wemos и я, по моему как раз через эту строку и исправил, но все осталось дома, а домой, больше попасть не могу. И ещё вопрос по поводу подпайки плеера к плате node mcu и wemos d1 mini, можно смело паять по схеме, которая в архиве на wemos, пины соответствуют с node mcu?

**Comment by aksenav2** [comment]
Поменял delay, та же проблема, не помогло. Подпаял плеер, в веб версии, тест файлов работает, еквалайзер работает, но что бы остановить воспроизведение, нужно перезагружать лампу. И не озвучиваются часы. Возможно, я не правильно скинул файлы на флешку и ещё, возможно в любую минуту озвучить часы?

**Comment by aksenav2** [comment]
Уже столько тестов провел и выяснил, что часы, во время будильника и минуты озвучивает, но будильник, никаким образом не выключается, продолжает играть и говорить, через каждую минуту время, пока не выключить от сети, не важно как и какими комбинациями нажимать на сенсорную кнопку. С вайфай, как я думал, решилась проблема, но в итоге, подключается, но один с десяти раз. Часы, каждый час не озвучивает, не знаю, что ещё попробовать, но если в будильнике время говорит, значит на флешке, файлы правильно скопированы.

**Comment by alvikskor** [comment]
Добрыйидень.    По поводу озвучивания.    Какой у вас чип на плеере? Внимательно прочитайте файл Version.txt . Описание последних 3-4 версий. Возможно вам надо закомментировать строку    #define DF_PLAYER_IS_ORIGINAL . Так же возможно нужно увеличить    задержки в Hardware Setings в web интерфейсе лампы.
  

  
По поводу подключения к роутеру ничего сказать не могу. Сегодня приехали две платы Wemos mini . Прошил , проверил как вы писали, с отключением питания, всё работает.   
  
Раскоментируйте строку    #define GENERAL_DEBUG и посмотрите уровень сигнала в мониторе Ардуино.    Возможно слишком слабый сигнал ( например вы закрыли антену платы чем-то металлическим или ещё что-то). Если уровень сигнала меньше -70dbm    может не подключаться. Нормальный уровень сигнала -30dbm ... -40dbm.
  

    

  
  
 С уважением Алексей Скоромный.

**Comment by aksenav2** [comment]
> Для [aksenav2] Александр. Добрый день. По поводу озвучивания. Какой у вас чип на плеере? Внимательно прочитайте файл Version.txt . Описание последних 3-4 версий. Возможно вам надо закомментировать строку #define DF_PLAYER_IS_ORIGINAL . Так же возможно нужно увеличить задержки в Hardware Setings в web интерфейсе лампы. По поводу подключения к роутеру ничего сказать не могу. Сегодня приехали две платы Wemos mini . Прошил , проверил как вы писали, с отключением питания, всё работает. Раскоментируйте строку #define GENERAL_DEBUG и посмотрите уровень сигнала в мониторе Ардуино. Возможно слишком слабый сигнал ( например вы закрыли антену платы чем-то металлическим или ещё что-то). Если уровень сигнала меньше -70dbm может не подключаться. Нормальный уровень сигнала -30dbm ... -40dbm.
> […](#)
> В 25 нояб. 2022 г. в 20:58, Александр ***@***.***> писал: Уже столько тестов провел и выяснил, что часы, во время будильника и минуты озвучивает, но будильник, никаким образом не выключается, продолжает играть и говорить, через каждую минуту время, пока не выключить от сети, не важно как и какими комбинациями нажимать на сенсорную кнопку. С вайфай, как я думал, решилась проблема, но в итоге, подключается, но один с десяти раз. Часы, каждый час не озвучивает, не знаю, что ещё попробовать, но если в будильнике время говорит, значит на флешке, файлы правильно скопированы. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

У меня и плеер не оригинал попался и esp8266 тоже какая-то странная. В итоге, хоть как-то поднастроил. А так же заменил голос на более приятный, создал папки для каждого эффекта с музыкальными файлами. Все же, мелкие баги наблюдаются, я думаю, это зависит от плат, у кого хорошо работает, у кого по хуже. Но вот с подключением, так проблема и не решилась, лампа, стоит в полтара метре от роутера, связь идеальная, роутер у меня мощный, это, что-то на программном уровне.

**Comment by aksenav2** [comment]
И ещё, перешёл, на другую прошивку, так как там веб версия удобнее. А могли бы вы, объеденить свою прошивку и эту, что я установил? Вытянуть из нее все эффекты, которые в вашей отсутствуют и вытянуть веб меню?
![Screenshot_2022-11-28-21-53-41-054_com opera browser](https://user-images.githubusercontent.com/110097689/204369263-acc80abe-d0f7-4d83-9643-7df524b6e5b3.jpg)

**Comment by alvikskor** [comment]
> И ещё, перешёл, на другую прошивку, так как там веб версия удобнее. А могли бы вы, объеденить свою прошивку и эту, что я установил? Вытянуть из нее все эффекты, которые в вашей отсутствуют и вытянуть веб меню? ![Screenshot_2022-11-28-21-53-41-054_com opera browser](https://user-images.githubusercontent.com/110097689/204369263-acc80abe-d0f7-4d83-9643-7df524b6e5b3.jpg)

Это и есть моя прошивка, в которой добавили три эффекта и в web интерфейс меню, украденные у @SlingMaster. В моей версии меню в web, пока не будет. Его сложно переделать под мультиязычность. Эффекты будут(уже есть, но не в релизе). Добавлю 4 или 5 доработанных эффектов, и еще чуть-чуть настроек. Плюс , работа над ошибками. Но сейчас очень сложно с электрикой, поэтому даты выхода релиза не загадываю.

**Comment by aksenav2** [comment]
> > И ещё, перешёл, на другую прошивку, так как там веб версия удобнее. А могли бы вы, объеденить свою прошивку и эту, что я установил? Вытянуть из нее все эффекты, которые в вашей отсутствуют и вытянуть веб меню?
> 
> Это и есть моя прошивка, в которой добавили три эффекта и в web интерфейс меню, украденные у @SlingMaster. В моей версии меню в web, пока не будет. Его сложно переделать под мультиязычность. Эффекты будут(уже есть, но не в релизе). Добавлю 4 или 5 доработанных эффектов, и еще чуть-чуть настроек. Плюс , работа над ошибками. Но сейчас очень сложно с электрикой, поэтому даты выхода релиза не загадываю.

Спасибо, что не забрасываете проект.

**Comment by aksenav2** [comment]
А есть ли возможность, подсоединить датчик температуры и что бы часы, говорили, каждый час время и температуру?

**Comment by aksenav2** [comment]
И ещё, сделать команду, что бы с сенсорной кнопки, можно было активировать, что бы в любое время, по нажатию, произносилось время.

**Comment by MishanyaTS** [comment]
> И ещё, сделать команду, что бы с сенсорной кнопки, можно было активировать, что бы в любое время, по нажатию, произносилось время.

По шестикратному нажатию воспроизводится время,  а вместо датчика тепмературы, лучше подключить микрофон, что бы эффекты на звук реагировали

**Comment by MishanyaTS** [comment]
> 
> > И ещё, перешёл, на другую прошивку, так как там веб версия удобнее. А могли бы вы, объеденить свою прошивку и эту, что я установил? Вытянуть из нее все эффекты, которые в вашей отсутствуют и вытянуть веб меню?
> 
> 
> Это и есть моя прошивка, в которой добавили три эффекта и в web интерфейс меню, украденные у @SlingMaster. В моей версии меню в web, пока не будет. Его сложно переделать под мультиязычность. Эффекты будут(уже есть, но не в релизе). Добавлю 4 или 5 доработанных эффектов, и еще чуть-чуть настроек. Плюс , работа над ошибками. Но сейчас очень сложно с электрикой, поэтому даты выхода релиза не загадываю.
> 

А когда у него было меню в web, у него как у вас вроде было, а потом вообще все убрал, оставил только настройки подключения. Это меню было подсмотрено из других источником и чуток переделано

**Comment by aksenav2** [comment]
А зачем делать мультиязычное веб с меню. Можно сделать несколько версий и перед прошивкой вставлять ту, которая нужна, укр или англ.

**Comment by alvikskor** [comment]
> А когда у него было меню в web,

Я не  правильно выразил свою мысль. Читать надо так : Это и есть моя прошивка, в которой добавили три эффекта , украденные у @SlingMaster ,и меню в Web-интерфейсе. 

> А зачем делать мультиязычное веб с меню.

Затем, что прошивка делалась, как мультиязычная. И, к тому же, из-за втрое боОльшего объёма передаваемых данных,  web-интерфейс становится ещё менее пороротливым. Особенно при слабом сигнеле wifi или в сильно загруженной сети.

По теме. Прошил еще две платы от другого продавца Wemos mini и NodeMCU Ver3 с модулем ESP-12e. Проверил коннект у себяв течении 2х суток в режиме регулярного отключения электроэнергии, и у соседей на других роутерах. Коннект стабильный. Думаю, ваши проблемы связаны с качеством используемой платы.


> А так же заменил голос на более приятный
На всякий случай. В папке Advert файлы подготовлены специальным образом. Они все одинаковой длительности и содержат тишину в начале и конце. Это надо иметь ввиду при замене. Так же я заметил, что скорость обращения плеера к заданному файлу ( и ,вообще , скорость обработки комманд) сильно зависит от скорости и объёма флешки ( карты) и от количества файлов на ней. Именно из-за этого регулировка времени проигрывания часов и минут, а так же задержка,  вынесены в интерфейс.

**Comment by aksenav2** [comment]
У меня, старенькая флешка на 4 гига, работает хорошо, с учётом, что на ней, ещё около 110 музыкальных файлов и с учётом, что не оригинальный плеер. Насчёт папки Advert, я сразу понял, когда заменил на свои и что-то не так стало разговаривать, так что пришлось отредактировать файлы, относящиеся к названию часов, минуты и так хорошо воспроизводит, без редактирования. Я скачивал приложения для андроид говорящие часы и вытянул от-туда более приятный голос девушки и убрал слово "ровно", заменив его на просто беззвучный файл. Так же, каждый файл, наростил в конце пустым фоном, что бы сделать одинаковую длинну ровно в 2.0 секунды, после в веб меню, настроил время проговаривания минут и часов. Если нужно, после, полных тестов, могу скинуть набор спокойной музыки, уже отсортированный по папкам и часы. И ещё, у меня, есть набор часов, на украинском языке, только он ещё не редактирован, могу, на досуге посмотреть, что можно сделать с ним.

**Comment by aksenav2** [comment]
А вот с подключением к роутеру, так и не решил проблему, перепробовав кучу вариантов. Перезагрузка роутера, не помогает, а вот нашел другой способ подключать, - включаю лампу и в это время, в настройках роутера, меняю какой-то пункт связанный с вайфай настройкой и роутер, перезагружает только сетевые настройки, это занимает около 5 секунд и лампа сразу подключается. Роутер ASUS rtx-55. Но этот вариант именно с этой платой, на других платах, когда был дома, такой проблемы не было.

**Comment by aksenav2** [comment]
Из-за бага с подключением, я лампу всегда держу включенной, хотелось бы конечно мосфет впаять, но у меня его нет, да и динамик поменять, он у меня так же не очень, а общем, мне пока нравится, как она разговаривает, каждый час (жаль температуру не говорит) и ещё, ночью не люблю полную темноту, использую, как ночник.  У нас, свет, слава богу не отключают, мы  сейчас живём в деревне и здесь нагрузка на сеть минимальная, может поэтому и не отключают .

**Comment by aksenav2** [comment]
У меня, на роутере много сидит устройств и веб меню лампы, которое с подменю, открывается идеально быстро и работает шустро, возможно, это зависит от мощности самого роутера.

**Comment by alvikskor** [comment]
> Если нужно, после, полных тестов, могу скинуть набор спокойной музыки, уже отсортированный по папкам и часы. И ещё, у меня, есть набор часов, на украинском языке, только он ещё не редактирован, могу, на досуге посмотреть, что можно сделать с ним.

Было бы хорошо. Можете выложить у себя в репозитории и тут дать ссылку. Только Гит не любит файлы более 50 МВ, поэтому архив с музыкой придется подробить. Украинские голосовые файлы лучше отдельным архивом. С вашего разрешения я его могу добавить в этот репозиторий. Пригодится и мне и другим людям

**Comment by aksenav2** [comment]
Вот ссылка на архив с музфайлами и русской озвучкой часов с более приятным голосом, переделал все секунды и часы, потестировал, разговаривает правильно и без глюков. В первых папках звуки камина, в папке номер 50 новогодние звуки. Насчет, воспроизведения музыки, да, иногда бывают глюки, но в том смысле, что не ту папку может начать воспроизводить, но это на некоторых эффектах, но еще, у меня и плеер не оригинал и плата глючная, так что, более точных тестов не могу сделать. https://drive.google.com/file/d/1KjDtmzlB3-8mzDB20-WgBVU-37k1Sysj/view?usp=share_link

**Comment by aksenav2** [comment]
По поводу украинской озвучки, оказалось, что там не хватает некоторых звуков минут и часов, наверное демо версия попалась. Буду искать полную, как найду, сразу переделаю и отправлю.

**Comment by alvikskor** [comment]
Спасибо.   
  
Не ту папку может воспроизводить по причине, что при выборе    папки с 20 по 90 ,лампа включает случайный выбор из диапазона (установленная папка) - (установленная папка+9). Если нужны фиксированные папки , то назначайте с 1 по 20 и с 90 по 99. Это есть в том же файле version.txt. Ознакомьтесь с ним поближе. :)
  

  

  
  
 С уважением Алексей Скоромный.

**Comment by aksenav2** [comment]
Спасибо огромное за совет, изучу. И кстати, нашел очень много голосов, как женских, так и мужских, включая и одну версию женского украинского. Украинский отредактирую, а остальные сброшу вам не обработанные, может пригодятся.

**Comment by aksenav2** [comment]
Переконвертировал и подогнал по размеру украинскую озвучку часов, голос, мне конечно не особо, но другой найти не смог, и так, пол дня ушло, много ньюансов было, надеюсь все будет правильно работать, у себя не провеял, вдруг что, отпишитесь. В архиве укр и другие, но не конвертированные голоса. https://drive.google.com/file/d/1r3hCiG_9wB2W9AfIyIvUNCBqCKqh7vnM/view?usp=share_link

**Comment by vadpol** [comment]
Олексій, вітання! Прошився останньою версією на нову D1 mini (не оригінал) з годинником, плеєром, кнопкою та моссфетом, кілька днів пропрацювало нормально, потім не розумію, що сталося. В режимі точки доступу все працює, як треба. Але якщо підключаюся до роутера, починається дуже повільна рекция на все керування що з кнопки, що з веб інтерфейсу, можна очікувати реакцію кілька хвилин, майже 5 або, навіть, більше. Хоча музика грає коректно і час відображається правильно, при чому крапки на годиннику миготять раз на 6 секунд (6 горять, 6 ні). Але відтворення ефектів дуууже повільне. При поверненні в режим точки доступу все знов нормально працює. Прошив нову чисту плату - все те ж саме одразу. Всі бібліотеки стоять, як рекомендовано, ArduinoJson шостої версії (останній реліз 6.20...). Не підкажете, куди копати, мабуть, щось збилось у налаштуваннях? Дуже дякую!

**Comment by alvikskor** [comment]
Вітаю. Я міркую, що у вас проблема десь у мережі. Може роутер лажае. Спробуйте змінити роутер (наприклад у друзів перевірте), або увімкніть на телефоні точку доступу и приєднайте до неі лампу. Перевірте на роутері _ можливо у вас на IP лампи ще другий девайс висить. На лампі перевірте налаштування управління кількома лампами. Якшо щщось підключали - вимкніть, знявши галочки и нажав кнопку Зберегти.

**Comment by vadpol** [comment]
Дуже дякую за відповідь, ця причина також має шанс на існування. Що я робив, щоб знайти цю причину: 

1.  Перезавантажував роутер (маю TP Link AX50 з WiFi6, один з останнього покоління, до цього ніяких проблем не помічалося). Хоча з частими відключеннями живлення може щось і пішло не так.
2. Під'єднувався до подовжувача WiFi з іншою назвою мережі, також перезавантажував кілька разів - все те саме.

Але! Проблему наразі поборов таким чином: 

1.  Взяв інший комп'ютер (практично новий ноутобук Lenovo), завантажив на нього чисту Arduino IDE 1.8.19 (ні в якому разі не 2.0.х, вони дуже ще глюкаві і не підтримують багато сторонніх функцій, наприклад LittleFS Data Uploader)
2. Встановив ESP8266 Core 2.7.4
3. Скачав цей репозитарій
4. Встановив бібліотекі тільки з нього (FastLED 3.4.0, ArduinoJson 5.13.5, таке інше), нічого більше не коментів чи розкоментів.
5. Залив прошивку на ті самі плати D1 mini, що глючили - и все запрацювало!

Зараз поставив на прогон, поки політ нормальний. Підозрюю якийсь конфлікт в бібліотеках на старому ПК, там стоїть дуже багато різних версій тих самих бібліотек, та їх переподключення якось підозріло працює, вказуєшь необхідну тобі версію, а воно не переключається не неї чомусь. Мабуть, саме IDE треба буде переставити, чи всі наявні бібліотеки знести та  встановити по новій, ще не пробував. Але сама причина так явно і не відкрилася поки що, но прояв був цікавий.

Буду спостерігати надалі, дам знати, якщо щось виявлю. Дуже дякую!

**Comment by vadpol** [comment]
![20230118_233033](https://user-images.githubusercontent.com/29047746/213299597-537df303-6ca8-424d-ac2d-f819a47f996e.jpg)
![20230118_233050](https://user-images.githubusercontent.com/29047746/213299728-a7f2ee2e-1ab1-456e-b799-81f97ef91fdf.jpg)

Ось маю ще таку платку на макетці зі старої лампи - з плеєром, мосфетом та кнопкою, але без таймера, Пізніше теж заллю цю прошивку до неї, тільки таймер закоменчу

**Comment by vadpol** [comment]
![image](https://user-images.githubusercontent.com/29047746/223462889-096b03cb-2fdc-48c5-a272-8c829131d169.png)
Не підкажете, що могло трапитись після включення, всі меню виглядають таким чином, дуже не хочеться розбирати лампу для перепрошивки. Перезавантаження не допомагаєю

**Comment by alvikskor** [comment]
Злетіла ФС. Точніше , файл config.json . Завантажте його через редактор ФС.

**Comment by vadpol** [comment]
Так, вдалось перепрошити по повітрю на версію 3.4. Зайшов на свою IPaddress/update, на щастя відобразилось у веб-інтерфейсі. Скомпілював файлову систему та прошивку в Ардуіно ІДЕ та загнав обидві по повітрю, все знов запрацювало. До того ганяв цю лампу десь два-три тижні, все було нормально, потім десь тиждень не вмикав, а коли вмикнув - так от трапилось. Маю якісний блок живлення Mean Well 5V 6A, що вбудувано в основу, не думаю, що він видав якусь перешкоду по живленню при вмиканні, хоча все можливе.... Дуже дякую за підказку!

**Comment by alvikskor** [comment]
Поправив Soud volume. Переробив послідовність вимикання лампи

**Comment by vadpol** [comment]
Прошився, дякую! Версія 3.41. Але 'volume' все ще чомусь без 'e'. Чи щось зробив не так? Лампа перезавантажувалась. 

![image](https://user-images.githubusercontent.com/29047746/225984537-cdb96898-15d1-4155-9bed-51010674a8c0.png)

**Comment by alvikskor** [comment]
> Прошився, дякую! Версія 3.41. Але 'volume' все ще чомусь без 'e'. Чи щось зробив не так? Лампа перезавантажувалась.
> 
> ![image](https://user-images.githubusercontent.com/29047746/225984537-cdb96898-15d1-4155-9bed-51010674a8c0.png)

А Ви файлову сістему теж обновили? Літера там!

**Comment by vadpol** [comment]
Зрозуміло, мабуть, залив стару. Перезаллю. Дуже дякую!

**Comment by alvikskor** [comment]
> Зрозуміло, мабуть, залив стару. Перезаллю. Дуже дякую!

Доречі, можете через редактор ФС змінити тільки один файл data\lang\lang.en.json.gz

**Comment by vadpol** [comment]
Гм, щось ніяк не вирулю... Завантажив по повітрю скомпільований за всіма правилами Web_Updater з файловою системою звідси по IPaddress/update в браузері -> Update success rebooting..., навіть якийсь новий звук програвся з динаміку. Але потім без коннекту до WiFi створюється своя точка доступу під назвою  ESP-7AA125, куди можна тільки зайти за 192.168.4.1/update, знов виходить меню завантаження, ллю скомпільовану за правилами свіжу прошивку, Update success rebooting і далі нічого не виходить, повне повертання на попередній крок  ->  без коннекту до WiFi створюється своя точка доступу під назвою  ESP-7AA125, куди можна тільки зайти за 192.168.4.1/update, знов виходить меню завантаження, і так по колу. Куди тепер копати? Дуже дякую!

**Comment by alvikskor** [comment]
Створення точки доступу з ім'ям  ESP-7AA125 вказуе на те, що немає файлової системи. 
При оновленни по повітрю у вас  є дві кнопки: "Firmware" та "FileSystem". Перша для завантаження прошивкі, друга, відповідно , для завантаження файлової системи. При компіляціі Ардуіно створює файли: FieryLedLampMultilingual.ino.bin це і є Firmware,  a  FieryLedLampMultilingual.mklittlefs.bin - є  Filesystem. За один раз ви можете завантажити тільке один файл. Або Firmware  або Filesystem. І кожен за допомогою своєї відповідної кнопки. 
Можливо я зазря це росповідаю , і ви все це знаєте. Но я тіке шо скачав з Гита (для чистоти експерименту) прошивку, скомпилював, залив в лампу - все працює як треба. Шось ви робете не так. Як вариант, поставте попередню версію, яка у вас працювала, а потім замінете файл data\lang\lang.en.json.gz за допомогою редактора ФС, щоб з'явилася потеряна літера.

**Comment by vadpol** [comment]
Велика дяка за ретельну відповідь! В принципі, так і робив, єдине, як виявилось, не заливав потрібний файл з файловою системою, чомусь думав, що WEB_Updater сам підтягує її разом з собою, бо раніше не було явної назви окремого bin файлу з нею. Тепер, за роз'яснення, скомпілював цей файл окремо та залив у ЄСПешку по повітрю, одразу запрацювало :) Дуже дякую Вам за Вашу працю та  терплячість!

**Comment by alvikskor** [comment]
Вирішено !
