### ISSUE TITLE
Новий Arduino IDE 2.2.1 не може використовувати json для загрузки файловоъ системи

### ISSUE THREAD

**Issue by Creo2005** [alvikskor/FieryLedLampMultilingual#28]
Я сьогодні встановив Arduino IDE 2.2.1 на macOS (но це не важливо).
Стари плугіни ESP8266 для завантаження файлової системи вже не працюють на новій IDE 2.2.1 +.
Тепер працює це
https://github.com/earlephilhower/arduino-littlefs-upload
оновіть документацію будь ласка.

**Comment by alvikskor** [comment]
Дякую. Додав плагин в архів. Оновив документацію.
