### ISSUE TITLE
В написі Слава Україні!, буква Ї та і відображаються іншими символами :(

### ISSUE THREAD

**Issue by Creo2005** [alvikskor/FieryLedLampMultilingual#30]
Колись ще в старій прошивці теж таке було.

**Comment by alvikskor** [comment]
Перевірив. Все працює правильно. Цей баг було виправлено доволі давно.
Спробуйте ще раз завантажити останній реліз прошивки, перепрошити лампу, і перевірити не змінюючі строку виводу з вашего телефону. Можливо саме телефон з Android 14 невірно передає кодіровку символів (хоча це малоімовірно, але...).

**Comment by Creo2005** [comment]
Добре, але з елефону не бачив що це можно змінити. Тільки в веб морді, та і не чіпав це. Спробую перепрошити. Дякую.

**Comment by Creo2005** [comment]
Перезалив прошивку, все одно буква ї -пише З, буква і - пише Ж. :(

**Comment by Creo2005** [comment]
Розібрався, я прошивав тільки файлову систему, а прошивку ні :) Лампа юзала стару прошивку :)
Тепер все добре. Дякую.

**Comment by alvikskor** [comment]
Добре. Питання закриваю. 👍

**Comment by Hajime-Hajime** [comment]
> Добре. Питання закриваю. 👍

Не нашел как написать тебе в ЛС, поэтому пишу сюда. Хорошая работа!

https://theins.ru/news/268176 - чуваку штраф в 500$ влепили за твой пранк
