### ISSUE TITLE
В веб інтерфейсі не зберігається налаштування галочок озвучки

### ISSUE THREAD

**Issue by Creo2005** [alvikskor/FieryLedLampMultilingual#31]
В мене в лампі немає озвучки та плеєра,
я закоментував все що до цього відносситься.
В веб інтерфейсі не зберігаються налаштування галочок, прибераю, а потім знову захожу і вони знову стоять.

**Comment by alvikskor** [comment]
> В мене в лампі немає озвучки та плеєра,
> я закоментував все що до цього відносситься.

Тому ці галочки і не обробляються. Це ніяк не впливає на роботу лампи, але, якщо це вас дратує, спробуйте наступне:
- разкоментуйте все , що стосується  плеєра. 
- разкоментуйте строку    //#define CHECK_MP3_CONNECTION                              // Закоментируйте эту строку если нужно, чтобы лампа не проверяла наличие связи с МР3 плеером
- Лампа буде обробляти всі галочки, але буде бачіти відсутність зв'язку с плеєром і не буде чекати відповіді від нього. 

Другий варіант - змінити значення змінних, відповідальних за ці галочки, у файлі config.json (Це можна зробити, безпосередньо, з веб інтерфейсу), а Потім перезавантажити лампу.

**Comment by Creo2005** [comment]
Доре, зрозумів. Дякую.
