### ISSUE TITLE
Ардуіно додаток, не скачуються ефекти з лампи.

### ISSUE THREAD

**Issue by Creo2005** [alvikskor/FieryLedLampMultilingual#32]
Пише що в лампі більше ефектів чим в додаку,
спроба скачати не вдала. 
Мова додатку не налаштовується - одразу вилітає, в мене Samsung s23: One UI 6, Android 14 - може з за цього.

**Comment by alvikskor** [comment]
Перевірив ще раз у себе. Все працюе добре. Але у мене  Android 12. Якщо в веб інтерфейсі є російська мова (колись забув видалити з релізу) то вона буде працювати не правильно і ефекти відображатись и завантажуватись у додаток не будуть. Спробуйте завантажити ще раз останній реліз прошивці та перевірити. Спробуйте перевірити з иншим телефоном (іншою версією Android).
Я не є автором додатку, і нажаль зв'язок з ним відсутній. Я не можу повпливати на роботу додатку. Якщо не запраціє , використовуйте веб інтерфейс. Він завжди працюе ,і можливостей налаштування там набагато більше.

**Comment by Creo2005** [comment]
> Перевірив ще раз у себе. Все працюе добре. Але у мене Android 12. Якщо в веб інтерфейсі є російська мова (колись забув видалити з релізу) то вона буде працювати не правильно і ефекти відображатись и завантажуватись у додаток не будуть. Спробуйте завантажити ще раз останній реліз прошивці та перевірити. Спробуйте перевірити з иншим телефоном (іншою версією Android). Я не є автором додатку, і нажаль зв'язок з ним відсутній. Я не можу повпливати на роботу додатку. Якщо не запраціє , використовуйте веб інтерфейс. Він завжди працюе ,і можливостей налаштування там набагато більше.

Мова російська в додатку, але в тедефоні українська, в додатку не можу змінити :( В вебі українська.

**Comment by Creo2005** [comment]
Доступ до вебінтерфейсц війшов тільки через /?user_seting

**Comment by Creo2005** [comment]
Отаке в хромі, в лев інтерфейсі показує на головні сторінці яка не завантажується
![Снимок экрана 2023-12-31 в 12 31 00](https://github.com/alvikskor/FieryLedLampMultilingual/assets/10849149/cdb9f045-28ef-4c05-ba2b-e7451a4c2463)

**Comment by alvikskor** [comment]
У вас десь баг у файлах. Можливо скачаний  архив пошкоджений. Скачайте останній реліз, та перепрошийте лампу. В данному випадку файлову систему. Хача , краще, все. І спробуйте спочатку керувати з компа. 
Це абсурд, але , може ваш андроід14 якось впливае. У мене нема чім це перевірити, але ... У мене назараз 5 ламп, всі з останньою прошивкою. Всі керуються з компа, андроід 12 та з iOS без помилок. 
Також перевірте живлення лампи. Можливо занадто великі пульсаціі чи занадто мале напруження.

**Comment by Creo2005** [comment]
ОК, з напругою все добре, даже дільше, 5.4в на холостому ході бж видає :)

**Comment by alvikskor** [comment]
Доброго дня. Після "правильної" перепрошивки додаток не перевіряли? Можливо він теж запрацював правильно?

**Comment by Creo2005** [comment]
> Доброго дня. Після "правильної" перепрошивки додаток не перевіряли? Можливо він теж запрацював правильно?

Перевірив, все добре :) ефекти з лампи завантажилися. То я протупив, бо тільки файлову систему оновив (бо стара злетіла чомусь), а про сам скетч забув, и юзалася стара прошивка з есп :)

**Comment by alvikskor** [comment]
Супер. Вопрос закриваю.   👍 
:)
